// <auto-generated />
using System;
using BugTracker.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugTracker.Migrations
{
    [DbContext(typeof(BugTrackerContext))]
    [Migration("20190225001951_InitialDbSetup")]
    partial class InitialDbSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BugTracker.DAL.Models.AssignedBug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BugId");

                    b.Property<int>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("BugId");

                    b.HasIndex("PersonId");

                    b.ToTable("AssignedBug");
                });

            modelBuilder.Entity("BugTracker.DAL.Models.Bug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateClosed");

                    b.Property<DateTime>("DateOpened");

                    b.Property<string>("Description");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Bug");
                });

            modelBuilder.Entity("BugTracker.DAL.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BugId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BugId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("BugTracker.DAL.Models.AssignedBug", b =>
                {
                    b.HasOne("BugTracker.DAL.Models.Bug", "Bug")
                        .WithMany("AssignedPeople")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BugTracker.DAL.Models.Person", "Person")
                        .WithMany("AssignedBugs")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BugTracker.DAL.Models.Person", b =>
                {
                    b.HasOne("BugTracker.DAL.Models.Bug")
                        .WithMany("People")
                        .HasForeignKey("BugId");
                });
#pragma warning restore 612, 618
        }
    }
}
